### ISSUE TITLE
issues with my game!!

### ISSUE THREAD

**Issue by eclipsate** [chjno/MEDP349-Fall17#11]
So I have two different sprites, one is an image of my dog and the others are obstacles. I can't get the obstacles to behind my dog and not in front. The code for my dog is before the code for the obstacles (I'm pretty sure) but it's still not right.

When the dog hits an obstacle, all the obstacles are supposed to turn red but they're not for some reason. Do I have a problem with the if statement?

Also, I need some way to keep score but can't figure out how to make a timer or stopwatch for that. 

Here is my code: http://alpha.editor.p5js.org/paigem/sketches/HJWBGOqaZ

**Comment by eclipsate** [comment]
Thanks so much! I'm also having trouble connecting the buttons with moving the dog. From the console log I can tell that everything is connected and the values are being read when I press the button and twist the potentiometer. I replaced the arrow key buttons with what i thought was the right code, but it's not working. Any ideas on what I'm doing wrong?

**Comment by chjno** [comment]
First, you need to make sure you're not processing your `data` variable when it's an empty string. You need to put your data processing logic inside the following if statement:

```javascript
if (data.length > 0){
  // do something with data
}
```

You're splitting data into an array of values, but then you need to assign these values to individual variables and convert them from strings to integers.

If you share your Arduino code I can also see if there are any issues on that end.

**Comment by eclipsate** [comment]
Yeah, I'm completely lost here. I have no idea how to link the Arduino code to p5. Do you have any office hours tomorrow?

`/*

*/

void setup() {
    Serial.begin(9600);
    pinMode(8, INPUT_PULLUP);
    pinMode(6, INPUT_PULLUP);
    pinMode(5, INPUT_PULLUP);
    pinMode(4, INPUT_PULLUP);
    pinMode(11, OUTPUT);
    
}

void loop() {
    int potVal = analogRead(A1);
    //int lightVal = analogRead(A2);
    int buttonVal = digitalRead(8);
       // int buttonVal = digitalRead(6);
            //int buttonVal = digitalRead(5);
            // int buttonVal = digitalRead(4);
    
    Serial.print(potVal);
    Serial.print(',');
     //Serial.print(lightVal);
    //Serial.print(',');
     Serial.print(buttonVal);
    Serial.println();
    
    if(obstacles.overlap(futress)) { 
      digitalWrite(11, HIGH);
    }
    

    
}
`

**Comment by chjno** [comment]
When you say you have no idea how to link Arduino to p5, can you be more specific? Because earlier you said it was connected and you were able to see the values in the console.

First, this doesn't look like it should be in your Arduino code. Otherwise your Arduino code looks fine.

```arduino
if(obstacles.overlap(futress)) { 
  digitalWrite(11, HIGH);
}
```

In p5, you're trying to use `buttonState` and `velocity` but where are you defining these variables? That's data coming from your Arduino, right? So you need to split the data into discrete values, convert them to integers, and assign them to the variables you're trying to use. I just added lines 86-87 based on what I think you're trying to do: http://alpha.editor.p5js.org/chjno/sketches/SJnXkmSAZ

I'm happy to do a Google Hangout/Skype session or meet in person tomorrow. Let me know what time works for you.

**Comment by eclipsate** [comment]
Ahh I get it now! I just needed to see your example. Everything makes perfect sense now. Thank you so much!!
